name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setting up Nodes
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: CI=true npm install
    - name: Run tests
      run: CI=true npm test
    - name: Build
      run: CI=true npm run build:prod
